language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
      dist: xenial
      sudo: true
  
install:
  - python -m pip install --upgrade pip
  - pip install -e .[test]
  - pip install codecov

script:
  - pytest
  - codecov
